apiVersion: batch/v1
kind: CronJob
metadata:
  name: bls-parser
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: parser
              image: parser:local
              command:
                - python3
                - main.py
                - --selenium_url
                - http://svc-selenium-chrome
                - --log-to-tg
              envFrom:
                - secretRef:
                    name: telegram-secret
