apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - parser.cron.yml
  - namespace.yml
  - selenium.deployment.yml
  - selenium.svc.yml
  - telegram.secret.yml
#
#configMapGenerator:
#  - name: parser-secret-v1
#    behavior: replace
#    files:
#      - ../../main.py
