apiVersion: batch/v1
kind: CronJob
metadata:
  name: bls-parser
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
#          volumes:
#            - name: script
#              configMap:
#                name: parser-script-v1
#                optional: false
          restartPolicy: Never
          containers:
            - name: parser
              resources:
                requests:
                  cpu: 100m
                  memory: 600m
                limits:
                  cpu: 300m
                  memory: 600m
              image: parser
#              volumeMounts:
#                - mountPath: /usr/app/
#                  name: script
              workingDir: /usr/app/
              command:
                - python3
                - main.py
                - --selenium_url
                - http://svc-selenium-chrome
                - --log-to-tg
              envFrom:
                - secretRef:
                    name: telegram-secret
