apiVersion: v1
kind: Service
metadata:
  name: svc-selenium-chrome
  labels:
    app: selenium-chrome
spec:
  ports:
    - port: 80
      targetPort: 4444
      protocol: TCP
  selector:
    app: selenium-chrome